# ModelNet40 inspection

Data structure: [x,y,z,normal_x,normal_y,normal_z]  
40 different classes

In [ ]:
from data_utils.ModelNetDataLoader import ModelNetDataLoader
import torch

root = 'data/modelnet40_normal_resampled/'
data = ModelNetDataLoader(root=root,split='train', uniform=False, normal_channel=False) # Using default vals as set in train_cls.py
DataLoader = torch.utils.data.DataLoader(data, batch_size=1, shuffle=True)
for point,label in DataLoader:
    print(f"Point: {point.shape}")
    print(f"Label: {label.shape}")
    break

print(point[:,0,:])
print(label)

The size of train data is 9843
Point: torch.Size([1, 1024, 6])
Label: torch.Size([1, 1])
tensor([[ 0.3757,  0.3254,  0.2975,  0.1168, -0.0176, -0.9930]])
tensor([[8]], dtype=torch.int32)


In [10]:
point.data.numpy()

array([[[-0.29555875,  0.29064938,  0.7729147 , -0.4712    ,
          0.2539    , -0.8447    ],
        [ 0.22454733, -0.41021997, -0.81656206,  0.6998    ,
         -0.4855    , -0.524     ],
        [-0.42110497, -0.41264176,  0.00866193, -0.9928    ,
         -0.09772   , -0.06942   ],
        ...,
        [ 0.05221193,  0.25160995, -0.7509797 ,  0.6338    ,
          0.1596    ,  0.7569    ],
        [-0.33634192, -0.23555966, -0.81927454,  0.        ,
         -0.9999    , -0.01139   ],
        [ 0.05531183,  0.05738147,  0.34522453, -0.7657    ,
          0.261     ,  0.5879    ]]], dtype=float32)

In [19]:
type(point[0,0,0].item())

float

# ShapeNet inspection

In [36]:
from data_utils.ShapeNetDataLoader import PartNormalDataset
import torch
from tqdm import tqdm

root = 'data/shapenetcore_partanno_segmentation_benchmark_v0_normal/'
data = PartNormalDataset(root=root, npoints=2048, split='train', normal_channel=False)
DataLoader = torch.utils.data.DataLoader(data, batch_size=512,shuffle=True,num_workers=3)

for point,label,target in tqdm(DataLoader):
    print(f"Point: {point.shape}")
    print(f"Label: {label.shape}")
    print(f"Target: {target.shape}")
    #max_label = target.max()
    break

#print(max_label)
#print(point[:,0,:])
#print(label.max())

  0%|          | 0/24 [00:00<?, ?it/s]

Point: torch.Size([512, 2048, 3])
Label: torch.Size([512, 1])
Target: torch.Size([512, 2048])


  0%|          | 0/24 [00:01<?, ?it/s]


# SemanticKitti inspection

In [ ]:
import numpy as np
import pandas as pd

def load_pc_semantic3d(filename):
    pc_pd = pd.read_csv(filename, header=None, delim_whitespace=True, dtype=np.float16)
    pc = pc_pd.values
    return pc

def load_pc_kitti(pc_path):
    scan = np.fromfile(pc_path, dtype=np.float32)
    scan = scan.reshape((-1, 4))
    points = scan[:, 0:3]  # get xyz
    return points

In [40]:
root = 'data/semantic_kitti_sample/'
data = load_pc_kitti(root + '000001.bin')
type(data)

# 'data/semantic_kitti_sample/000001.bin'

numpy.ndarray

In [49]:
import datetime
snapshot_time = datetime.datetime.now().strftime("%d-%m-%Y_%H-%M-%S")
print(snapshot_time)

12-11-2024_15-25-28


In [64]:
try:
    if newest_state is not None:
        print("Loading model from state")
        del newest_state
except NameError:
    print("No state found")
    newest_state = 24




No state found
